import type { WeaponConfig, WeaponId } from '@/types';

export const WEAPONS: Record<WeaponId, WeaponConfig> = {
  'water-gun': {
    id: 'water-gun',
    nameHiragana: 'みずでっぽう',
    emoji: '🔫',
    damage: 8,
    rangeMeters: 35,
    cooldownMs: 130,
    ammoMax: 60,
    ammoPerShot: 1,
    reloadMs: 1200,
    projectileSpeed: 42,
    gravity: 5,
    splashRadius: 0,
    pellets: 1,
    spreadRad: 0.012,
    // せなかのタンクからじわじわ回復する。みずぎれで何もできない時間を作らない。
    refillPerSecond: 6,
    refillDelayMs: 1100,
  },
  'balloon-launcher': {
    id: 'balloon-launcher',
    nameHiragana: 'みずふうせん',
    emoji: '🎈',
    damage: 32,
    rangeMeters: 40,
    cooldownMs: 900,
    ammoMax: 6,
    ammoPerShot: 1,
    reloadMs: 1800,
    projectileSpeed: 26,
    gravity: 16,
    splashRadius: 3.6,
    pellets: 1,
    spreadRad: 0.02,
    refillPerSecond: 0,
    refillDelayMs: 0,
  },
  'bubble-shower': {
    id: 'bubble-shower',
    nameHiragana: 'バブルシャワー',
    emoji: '🫧',
    damage: 7,
    rangeMeters: 12,
    cooldownMs: 700,
    ammoMax: 12,
    ammoPerShot: 1,
    reloadMs: 1600,
    projectileSpeed: 34,
    gravity: 6,
    splashRadius: 0,
    pellets: 7,
    spreadRad: 0.22,
    refillPerSecond: 0,
    refillDelayMs: 0,
  },
};

export const WEAPON_ORDER: WeaponId[] = ['water-gun', 'balloon-launcher', 'bubble-shower'];
